#!/bin/bash
git add .
git commit -m 'Create a magic file school.mgc that can be used with the command file to detect School data files. School data files always contain the string SCHOOL at offset 0.'
git push
